// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.


/**
 * Generated API client with HTTP methods
 */
export class ApiClient {
  /** Base URL for API requests */
  baseUrl: string;
  /** Default headers for requests */
  headers?: Record<string, string>;
  /**
   * Initialize the API client
   */
  constructor(baseUrl: string, headers?: Record<string, string>) {
    this.baseUrl = baseUrl;
    this.headers = headers;
  }
  /**
   * Make a GET request
   */
  get(path: string): Promise<any> {
    return fetch(`${this.baseUrl}${path}`, {
      method: 'GET',
      headers: this.headers,
    }).then(response => response.json());
  }
  /**
   * Make a POST request
   */
  post(path: string, body?: any): Promise<any> {
    return fetch(`${this.baseUrl}${path}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        ...this.headers,
      },
      body: body ? JSON.stringify(body) : undefined,
    }).then(response => response.json());
  }
}