import { OrderStatus } from './order-status';
// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.


/**
 * Order model
 */
export interface Order {
  complete?: any;
  id?: any;
  pet_id?: any;
  quantity?: any;
  ship_date?: any;
  status?: any | OrderStatus;
}