import { Category } from './category';
import { PetStatus } from './pet-status';
// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.


/**
 * Pet model
 */
export interface Pet {
  category?: any | Category;
  id?: any;
  name: any;
  photo_urls: Array<any>;
  status?: any | PetStatus;
  tags?: Array<any>;
}