// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.


/**
 * User model
 */
export interface User {
  email?: any;
  first_name?: any;
  id?: any;
  last_name?: any;
  password?: any;
  phone?: any;
  user_status?: any;
  username?: any;
}