// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.

import { BaseAPI } from '../runtime/api';
import { Configuration } from '../runtime/config';


/**
 * API client for default operations
 */
export class DefaultApi extends BaseAPI {
  /**
   * Initialize the API client
   */
  constructor(configuration?: Configuration) {
    super(configuration);
  }
  gettest(): Promise<Response> {
    const url = this.configuration?.basePath || '';
    return this.request({ url, init: { method: 'DELETE' } });
  }
}