// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.

/**
 * Convert typed object to JSON
 */
export function ToJSON<T>(value: T): any {
  // TODO: Implement function body
  throw new Error('Not implemented');
}
/**
 * Convert JSON object to typed object
 */
export function FromJSON<T>(json: any): T {
  // TODO: Implement function body
  throw new Error('Not implemented');
}