//! Template function for generating file headers

/// Template function for generating file headers
pub fn do_not_edit() -> String {
    const DO_NOT_EDIT: &str = r#"// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file."#;
    DO_NOT_EDIT.to_string()
}
