// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.


/**
 * Configuration for API client
 */
export interface Configuration {
  /** Base path for API requests */
  basePath?: string;
  /** Username for authentication */
  username?: string;
  /** Password for authentication */
  password?: string;
  /** API key for authentication */
  apiKey?: string;
  /** Access token for authentication */
  accessToken?: string;
  /** Additional headers for requests */
  headers?: { key: string; value: string };
}
/**
 * Configuration parameters for API client
 */
export interface ConfigurationParameters {
  /** Base path for API requests */
  basePath?: string;
  /** Username for authentication */
  username?: string;
  /** Password for authentication */
  password?: string;
  /** API key for authentication */
  apiKey?: string;
  /** Access token for authentication */
  accessToken?: string;
}