// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.


/**
 * Promise type for parsed response value
 */
export type Promise<T> = Promise<T>;
/**
 * Convert typed object to JSON
 */
export function ToJSON(value: T): any {
  // TODO: Implement function body
}
/**
 * Convert JSON object to typed object
 */
export function FromJSON(json: any): T {
  // TODO: Implement function body
}