// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.

/** API response model */
export interface ApiResponse {
code?: number | null,
message?: string | null,
type?: string | null
}

export function instanceOfApiResponse(value: object): value is ApiResponse {
    return true;
}

export function ApiResponseFromJSON(json: any): ApiResponse {
    return ApiResponseFromJSONTyped(json, false);
}

export function ApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponse {
    if (json == null) {
        return json;
    }
    return {
        'code': json['code'] ?? undefined,
        'message': json['message'] ?? undefined,
        'type': json['type'] ?? undefined,
    };
}

export function ApiResponseToJSON(value?: ApiResponse | null): any {
    return ApiResponseToJSONTyped(value, false);
}

export function ApiResponseToJSONTyped(value?: ApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        'code': value['code'],
        'message': value['message'],
        'type': value['type'],
    };
}

export const ApiResponsePropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
};