// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.

/** API response model */
export interface ApiResponse {
code?: number | null,
message?: string | null,
type?: string | null
}