// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.

/**
 * Category model
 */
export interface Category {
  /**
   * Category ID
   */
  id?: number | null,
  /**
   * Category name
   */
  name?: string | null,
}