// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.


/**
 * Category model
 */
export interface Category {
  id?: number | null | null;
  name?: string | null | null;
}