// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.

/** Order model */
export interface Order {
complete?: boolean | null,
id?: number | null,
pet_id?: number | null,
quantity?: number | null,
ship_date?: string | null,
status?: null | "approved" | "delivered" | "placed"
}