// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.

/**
 * Order status enum
 */
export enum OrderStatus {
Placed = "placed",
Approved = "approved",
Delivered = "delivered"
}