// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.

/**
 * Pet model
 */
export interface Pet {
  category?: null | {
      id: number | null;
      name: string | null;
    },
  /**
   * Pet ID
   */
  id?: number | null,
  /**
   * Pet name
   */
  name: string,
  photo_urls: Array<string>,
  status?: null | "available" | "pending" | "sold",
  tags?: Array<{
      id: number | null;
      name: string | null;
    }>,
}