// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.

/**
 * Tag model
 */
export interface Tag {
/**
 * Tag ID
 */
id?: number | null,
/**
 * Tag name
 */
name?: string | null
}