// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.

/** User model */
export interface User {
email?: string | null,
first_name?: string | null,
id?: number | null,
last_name?: string | null,
password?: string | null,
phone?: string | null,
user_status?: number | null,
username?: string | null
}