// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.


/**
 * User model
 */
export interface User {
  email?: string | null | null;
  first_name?: string | null | null;
  id?: number | null | null;
  last_name?: string | null | null;
  password?: string | null | null;
  phone?: string | null | null;
  user_status?: number | null | null;
  username?: string | null | null;
}