[package]
name = "openapi-nexus-plugin"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
serde.workspace = true
serde_json.workspace = true
snafu.workspace = true
utoipa.workspace = true
