//! Constants for TypeScript emission

/// Generated file header comment
pub const GENERATED_FILE_HEADER: &str = r#"// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.
"#;
