// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.

export class FetchError extends Error {
    cause: Error;

    constructor(cause: Error, msg?: string) {
        super(msg);
        this.cause = cause;
    }
}
