// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.

export class TextApiResponse {
    raw: Response;

    constructor(raw: Response) {
        this.raw = raw;
    }

    async value(): Promise<string> {
        return await this.raw.text();
    }
}
