// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.

export class JSONApiResponse<T> {
    raw: Response;
    transformer: ResponseTransformer<T>;

    constructor(raw: Response, transformer: ResponseTransformer<T> = (jsonValue: any) => jsonValue) {
        this.raw = raw;
        this.transformer = transformer;
    }

    async value(): Promise<T> {
        return this.transformer(await this.raw.json());
    }
}
