// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.

export class RequiredError extends Error {
    field: string;

    constructor(field: string) {
        super(`Field ${field} is required`);
        this.field = field;
    }
}
