// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.

export class ResponseError extends Error {
    response: Response;

    constructor(response: Response, msg?: string) {
        super(msg);
        this.response = response;
    }
}
