// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.

/**
 * Basic object with properties
 */
export interface BasicObject {
  /**
   * Whether the object is currently active
   */
  active?: boolean,
  /**
   * Unique identifier for the object
   */
  id: number,
  /**
   * Human-readable name of the object
   */
  name: string,
}