// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.

export interface ComplexNestedObject {
id: number,
user: {
  id: number;
  profile: {
    contact: {
      addresses: Array<{
          city: string;
          street: string;
          zip: string;
        }>;
      email: string;
      phone: string;
    };
    firstName: string;
    lastName: string;
  };
}
}