// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.

/**
 * Object with nested object property
 */
export interface NestedObject {
  /**
   * Additional metadata about the object
   */
  metadata?: { created: string },   /**
   * User information object
   */
  user?: { id: number; name: string },
}