// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.

/** Nullable string type (OpenAPI 3.1.2 style) */
export type NullableString = string | null