// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.

/**
 * Object not allowing additional properties
 */
export interface ObjectWithAdditionalPropertiesFalse {
name: string
}