// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.

/**
 * Object allowing any additional properties
 */
export interface ObjectWithAdditionalPropertiesTrue {
  name: string,   /**
   * Additional properties
   */
  [key: string]: any,
}