// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.

/**
 * Required enum field in object
 */
export interface RequiredEnumField {
  status: "active" | "inactive";
}