// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.

export interface ErrorContext {
    fetch: FetchAPI;
    url: string;
    init: RequestInit;
    error: any;
    response?: Response;
}
