// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.

export interface Middleware {
    pre?: (context: RequestContext) => Promise<FetchParams | void>;
    post?: (context: ResponseContext) => Promise<Response | void>;
    onError?: (context: ErrorContext) => Promise<Response | void>;
}
