// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.

import { BaseAPI, RequestContext } from '../runtime/api';

import { Configuration } from '../runtime/config';

/**
 * API client for default operations
 */
export class DefaultApi extends BaseAPI {
  /**
   * Initialize the API client
   */
  constructor(configuration?: Configuration) {
    super(configuration);
  }
  /**
   * Test endpoint
   */
  test(): Promise<Response> {
    // TODO: Implement method
    throw new Error('Not implemented');
  }
}