[package]
name = "generate-openapi"
version.workspace = true
edition.workspace = true
publish = false

[[bin]]
name = "generate-openapi"
path = "generate-openapi.rs"

[dependencies]
openapi-generator-petstore-example.workspace = true
serde_norway.workspace = true
utoipa.workspace = true
