// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.


/**
 * API client for pet operations
 */
export class PetApi extends runtime.BaseAPI {
  /**
   * Initialize the API client
   */
  constructor(configuration?: Configuration) {
    super(configuration);
  }
  /**
   * Add a new pet to the store
   */
  addPet(body: Pet): Promise<Pet> {
    // TODO: Implement method
  }
  /**
   * Update an existing pet
   */
  updatePet(body: Pet): Promise<Pet> {
    // TODO: Implement method
  }
  /**
   * Find pets by status
   */
  findPetsByStatus(status: string): Promise<Array<string>> {
    // TODO: Implement method
  }
  /**
   * Find pets by tags
   */
  findPetsByTags(tags: Array<string>): Promise<Array<string>> {
    // TODO: Implement method
  }
  /**
   * Find pet by ID
   */
  getPetById(petId: string): Promise<Pet> {
    // TODO: Implement method
  }
  /**
   * Update a pet in the store with form data
   */
  updatePetWithForm(petId: string, name?: string, status?: string): Promise<Pet> {
    // TODO: Implement method
  }
  /**
   * Delete a pet
   */
  deletePet(petId: string): Promise<Response> {
    // TODO: Implement method
  }
  /**
   * Upload an image
   */
  uploadFile(petId: string, additionalMetadata?: string): Promise<ApiResponse> {
    // TODO: Implement method
  }
}