// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.


/**
 * API client for user operations
 */
export class UserApi extends runtime.BaseAPI {
  /**
   * Initialize the API client
   */
  constructor(configuration?: Configuration) {
    super(configuration);
  }
  /**
   * Create user
   */
  createUser(body: User): Promise<User> {
    // TODO: Implement method
  }
  /**
   * Creates list of users with given input array
   */
  createUsersWithListInput(body: Array<string>): Promise<User> {
    // TODO: Implement method
  }
  /**
   * Logs user into the system
   */
  loginUser(username?: string, password?: string): Promise<Response> {
    // TODO: Implement method
  }
  /**
   * Logs out current logged in user session
   */
  logoutUser(): Promise<Response> {
    // TODO: Implement method
  }
  /**
   * Get user by user name
   */
  getUserByName(username: string): Promise<User> {
    // TODO: Implement method
  }
  /**
   * Update user
   */
  updateUser(username: string, body: User): Promise<Response> {
    // TODO: Implement method
  }
  /**
   * Delete user
   */
  deleteUser(username: string): Promise<Response> {
    // TODO: Implement method
  }
}