[package]
name = "openapi-generator"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

openapi-generator-core.workspace = true
openapi-generator-typescript.workspace = true